logging:
  level:
    root: INFO

server:
  port: 8080

mybatis:
  configLocation: classpath:mybatis-config.xml
  mapperLocations: classpath*:**/*Mapper.xml

spring:
  application:
    name: data-report
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql.frag.com/lhj
    username: lhj
    password: 123
    druid:
      initial-size: 16
      min-idle: 16
      max-active: 64
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
