logging:
  level:
    root: INFO

taotie: 
  queuePower: 6
  pollThreadPower: 1
  benchCommitNum: 4000
  commitThreadNum: 10
  queueCapacityFactor: 1.0
  offerTimeout: 10
  pollTimeout: 100

server:
  port: 8080
#  tomcat:
#    maxThreads: 800
#    minSpareThreads: 500
#    maxConnections: 4000
#    acceptCount: 1000

